all: help
TAG = annorepo
DOCKER_DOMAIN = registry.diginfra.net/tt
SHELL=/bin/bash
CLIENT_SRC=$(shell find client/src/ -type f)
COMMON_SRC=$(shell find common/src/ -type f)
version_fn = $(shell cat .make/.version 2>/dev/null)

.SECONDARY:
.DELETE_ON_ERROR:

RED=\033[1;31m
GREEN=\033[1;32m
YELLOW=\033[1;33m
BLUE=\033[1;34m
RESET=\033[0m

.make:
	mkdir -p .make

.make/.version: pom.xml | .make
	mvn help:evaluate -Dexpression=project.version -q -DforceStdout > .make/.version

server/target/annorepo-server-$(call version_fn).jar: .make/.version  $(shell find server/src common/src -type f) pom.xml server/pom.xml
	mvn --projects server --also-make package

client/target/annorepo-client-$(call version_fn).jar: .make/.version  $(shell find client/src common/src -type f) pom.xml client/pom.xml
	mvn --projects client --also-make package

.PHONY: build
build: .make/.version server/target/annorepo-server-$(call version_fn).jar client/target/annorepo-client-$(call version_fn).jar

.PHONY: build-server
build-server: .make/.version server/target/annorepo-server-$(call version_fn).jar

.PHONY: build-client
build-client: .make/.version client/target/annorepo-client-$(call version_fn).jar client/readme.md

.make/install-client: client/pom.xml $(CLIENT_SRC) common/pom.xml $(COMMON_SRC) | .make
	mvn --projects client --also-make install
	@touch $@

.PHONY: install-client
install-client: .make/install-client

.PHONY: run-server-with-auth
run-server-with-auth: build-server
	@make start-mongodb
	AR_ROOT_API_KEY=root java -jar server/target/annorepo-server-$(call version_fn).jar server config-with-auth.yml

.PHONY: run-server-without-auth
run-server-without-auth: build-server
	@make start-mongodb
	java -jar server/target/annorepo-server-$(call version_fn).jar server config-without-auth.yml

.PHONY: run-env
run-env: build-server
	java -jar server/target/annorepo-server-$(call version_fn).jar env

.PHONY: docker-run
docker-run: k8s/local/docker-compose.yml
	cd k8s/local && docker compose up &

.PHONY: docker-stop
docker-stop: k8s/local/docker-compose.yml
	cd k8s/local && docker compose down

.make/.docker: .make/.version k8s/annorepo-server/Dockerfile-multistage
	docker build -t $(TAG):$(call version_fn) -f k8s/annorepo-server/Dockerfile-multistage .
	@touch $@

.PHONY: docker-image
docker-image: .make/.docker

.make/.push-server: build k8s/annorepo-server/Dockerfile
	docker build -t $(TAG):$(call version_fn) --platform=linux/amd64 -f k8s/annorepo-server/Dockerfile .
	docker tag $(TAG):$(call version_fn) $(DOCKER_DOMAIN)/$(TAG):$(call version_fn)
	docker push $(DOCKER_DOMAIN)/$(TAG):$(call version_fn)
	@touch $@

.make/.push-updater: k8s/updater/Dockerfile
	docker build -t $(TAG)-updater:$(call version_fn) --platform=linux/amd64 -f k8s/updater/Dockerfile .
	docker tag $(TAG)-updater:$(call version_fn) $(DOCKER_DOMAIN)/$(TAG)-updater:$(call version_fn)
	docker push $(DOCKER_DOMAIN)/$(TAG)-updater:$(call version_fn)
	@touch $@

.PHONY: push
push:   clean build-server .make/.push-server .make/.push-updater
	@make browse-registry

.PHONY: clean
clean:
	rm -rf .make */src/generated/*/*
	mvn clean

.PHONY: version-update
version-update:
	mvn versions:set && mvn versions:commit && find . -name dependency-reduced-pom.xml -delete
	make client/readme.md

.make/.deploy: build-client
	export GPG_TTY=$(tty)
	mvn clean install
	mvn --projects client --also-make deploy -P release
	open https://repo.maven.apache.org/maven2/io/github/knaw-huc/annorepo-client/
	open https://central.sonatype.com/search?q=annorepo
	@touch $@

.PHONY: deploy
deploy:	.make/.deploy

.make/.dokka: $(shell find */src -type f) pom.xml */pom.xml
	mvn dokka:dokka --projects client --also-make
	rm -rf client/dokka
	mv client/target/dokka client/dokka
	rm -rf common/dokka
	mv common/target/dokka common/dokka
	@touch $@

.PHONY: dokka
dokka:	.make/.dokka

client/readme.md: client/src/test/resources/readme.md client/pom.xml
	mvn --projects client --also-make resources:testResources
	echo "<!--- DO NOT EDIT THIS FILE! This file is generated from client/src/test/resources/readme.md; edit that file instead. -->" > client/readme.md
	cat client/target/test-classes/readme.md >> client/readme.md

.PHONY: release
release:
	git pull && \
	git push && \
	make version-update && \
	git commit -a -m "bump version to $(call version_fn)" && \
	git push && \
	gh release create v$(call version_fn) && \
	make deploy

.PHONY: test
test:
	mvn test -Dmaven.plugin.validation=VERBOSE

.PHONY: start-mongodb
start-mongodb:
	docker start mongodb6 || docker run --name mongodb6 -d -p 27017:27017 -v ~/local/mongo:/data/db mongo:6.0.27

.PHONY: set-log-level-debug
set-log-level-debug:
	curl -X POST -d "logger=ROOT&level=DEBUG" http:/localhost:8081/tasks/log-level

.PHONY: set-log-level-info
set-log-level-info:
	curl -X POST -d "logger=ROOT&level=INFO" http:/localhost:8081/tasks/log-level

.make/compiled-protocol-buffers: common/src/main/proto/*.proto | .make
	mkdir -p common/target/python
	python -m grpc_tools.protoc \
	-I common/src/main/proto \
	--python_out=common/target/python \
	--pyi_out=common/target/python \
	--grpc_python_out=common/target/python \
	common/src/main/proto/*.proto
#	protoc	--proto_path=common/src/main/proto \
#	--python_out=common/target/python \
#	--pyi_out=common/target/python \
#	--grpc_python_out=common/target/python \
#	common/src/main/proto/*.proto
	@touch $@

.PHONY: compile-protocol-buffers
compile-protocol-buffers: .make/compiled-protocol-buffers

current_branch=$(shell git branch --show-current)

.PHONY: git-pull
git-pull:
	git checkout main && git pull
	@echo
	git checkout develop && git merge main && git pull && git push
	#git checkout develop && git rebase main && git pull && git push
	@echo
	git checkout $(current_branch)

.PHONY: browse-registry
browse-registry:
	@open "https://registry.diginfra.net/browser/repo/tt/annorepo?sort_tags_by=version&sort_tags_order=desc"

.PHONY: help
help:
	@echo -e "make-tools for $(GREEN)$(TAG)$(RESET)"
	@echo
	@echo -e "Please use \`$(YELLOW)make <target>$(RESET)', where $(YELLOW)<target>$(RESET) is one of:"
	@echo -e "  $(BLUE)git-pull$(RESET)                  - to pull git changes from the main branch ( + update the develop branch)"
	@echo -e "  $(BLUE)test$(RESET)                     - to test the project"
	@echo -e "  $(BLUE)clean$(RESET)                     - to remove generated files"
	@echo -e "  $(BLUE)compile-protocol-buffers$(RESET)  - to compile all .proto files"
	@echo -e "  $(BLUE)install-client$(RESET)            - to install the client code in the local maven repository"
	@echo
	@echo -e "  $(BLUE)build$(RESET)                     - to test and build the project"
	@echo -e "  $(BLUE)build-server$(RESET)              - to test and build just the server"
	@echo -e "  $(BLUE)build-client$(RESET)              - to test and build just the client"
	@echo
	@echo -e "  $(BLUE)start-mongodb$(RESET)             - to start a local mongodb"
	@echo -e "  $(BLUE)run-server-with-auth$(RESET)      - to start the server app with authorization on"
	@echo -e "  $(BLUE)run-server-without-auth$(RESET)   - to start the server app with authorization off"
	@echo -e "  $(BLUE)run-env$(RESET)                   - to run the annorepo env command"
	@echo -e "  $(BLUE)set-log-level-debug$(RESET)       - to set the log level of the server app to DEBUG"
	@echo -e "  $(BLUE)set-log-level-info$(RESET)        - to set the log level of the server app to INFO"
	@echo
	@echo -e "  $(BLUE)docker-run$(RESET)                - to start the server app in docker"
	@echo -e "  $(BLUE)docker-stop$(RESET)               - to stop the server app in docker"
	@echo
	@echo -e "  $(BLUE)docker-image$(RESET)              - to build the docker image of the app (¹)"
	@echo -e "  $(BLUE)push$(RESET)                      - to push the linux/amd64 docker image to registry.diginfra.net (¹)"
	@echo -e "  $(BLUE)browse-registry$(RESET)           - to open the registry.diginfra.net registry browser"
	@echo
	@echo -e "  $(BLUE)version-update$(RESET)            - to update the project version"
	@echo -e "  $(BLUE)dokka$(RESET)                     - to generate dokka html"
	@echo -e "  $(BLUE)deploy$(RESET)                    - to deploy annorepo-client and annorepo-common"
	@#echo -e "  $(BLUE)release$(RESET)                   - to create a new release on github + deploy the new client"
	@echo
	@echo "¹) for test purposes only, the public docker image is built by github actions upon a release"
